// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcoIP4id0zEsMRlysgDJQQCdM1N7bPDac',
    appId: '1:146829936187:web:89d0b9ed5e3c1d2a8d7e1e',
    messagingSenderId: '146829936187',
    projectId: 'danny-whatsapp',
    authDomain: 'danny-whatsapp.firebaseapp.com',
    storageBucket: 'danny-whatsapp.appspot.com',
    measurementId: 'G-6Y4YYRR83L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPv1KonpvY9QoJsEhmizBYyqrNJwRey9I',
    appId: '1:146829936187:android:f081a82f9bc42c2c8d7e1e',
    messagingSenderId: '146829936187',
    projectId: 'danny-whatsapp',
    storageBucket: 'danny-whatsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdfrHbU_rVg9SJrRQljPlQCVblr39GQq0',
    appId: '1:146829936187:ios:7977a778aec2d6d08d7e1e',
    messagingSenderId: '146829936187',
    projectId: 'danny-whatsapp',
    storageBucket: 'danny-whatsapp.appspot.com',
    iosClientId: '146829936187-a7v12isbba7o7o750bqjq917f5gnpkrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dannyChats',
  );
}
